server:
  port: 8081
spring:
  rabbitmq:
    publisher-returns: true
    publisher-confirm-type: correlated
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator